# This file was generated by GoReleaser. DO NOT EDIT.
cask "kapi" do
  version "1.3.1-beta.1"

  on_macos do
    on_arm do
      sha256 "65ca6270b3a4da159958c0792abcf83bd7de244913dcfd46403e527799b5eb0e"
      url "https://github.com/slouowzee/KAPI/releases/download/v#{version}/KAPI_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b6aa5df0ddbd2400d7991ad9217dea93cfc23d6c0a6543fd1a4b8320b1037d90"
      url "https://github.com/slouowzee/KAPI/releases/download/v#{version}/KAPI_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9cad7335f1ce2df348652614d87e966b565833d5ee342a7be6ac6b1669f3b23b"
      url "https://github.com/slouowzee/KAPI/releases/download/v#{version}/KAPI_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8987cf75944dcdefc120945d90b789235070cfd95363d191d568f79f77bfef01"
      url "https://github.com/slouowzee/KAPI/releases/download/v#{version}/KAPI_linux_amd64.tar.gz"
    end
  end

  name "kapi"
  desc "A Go-based interactive TUI CLI for project scaffolding"
  homepage "https://github.com/slouowzee/kapi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kapi"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kapi"]
    end
  end

  # No zap stanza required
end
