# This file was generated by GoReleaser. DO NOT EDIT.
cask "kapi" do
  version "1.3.1-beta.1"

  on_macos do
    on_arm do
      sha256 "2ac267ddfd4b013552ff902ef2e49533d64e2f802d4d23d79c6f93a1185f2b04"
      url "https://github.com/slouowzee/KAPI/releases/download/v#{version}/KAPI_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "23fc6fc9470454f9f15aea4bea5551cc8b81bfd7746c58c0e05496e1614bb768"
      url "https://github.com/slouowzee/KAPI/releases/download/v#{version}/KAPI_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ac5ae7e513a28a6343d70c01c5829d901e59b9f97d360eeb5ff3853b70a61b02"
      url "https://github.com/slouowzee/KAPI/releases/download/v#{version}/KAPI_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "85531289b05a013077c41fc60079d34549f7d7de69c41f47e8c58012ea308137"
      url "https://github.com/slouowzee/KAPI/releases/download/v#{version}/KAPI_linux_amd64.tar.gz"
    end
  end

  name "kapi"
  desc "A Go-based interactive TUI CLI for project scaffolding"
  homepage "https://github.com/slouowzee/kapi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kapi"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kapi"]
    end
  end

  # No zap stanza required
end
