# This file was generated by GoReleaser. DO NOT EDIT.
cask "kapi" do
  version "1.3.0-beta.1"

  on_macos do
    on_arm do
      sha256 "f7579d2ecadb523df1f36f227ac86395449d98e7737bedc1f21687eacc4a0d97"
      url "https://github.com/slouowzee/KAPI/releases/download/v#{version}/KAPI_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "81166f553f993c19b85e820508b8fbf6e1601798505840a37a4b98c324e2069b"
      url "https://github.com/slouowzee/KAPI/releases/download/v#{version}/KAPI_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "84256dc86cff057240029c478386a5cd60fab3f12a938e99c4b116527a493dcf"
      url "https://github.com/slouowzee/KAPI/releases/download/v#{version}/KAPI_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "eb6fd098aeff83dad17e320094d7e46671a008ee3d2bb05102cee2d880d7a73b"
      url "https://github.com/slouowzee/KAPI/releases/download/v#{version}/KAPI_linux_amd64.tar.gz"
    end
  end

  name "kapi"
  desc "A Go-based interactive TUI CLI for project scaffolding"
  homepage "https://github.com/slouowzee/kapi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kapi"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kapi"]
    end
  end

  # No zap stanza required
end
