# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kapi < Formula
  desc "A Go-based interactive TUI CLI for project scaffolding"
  homepage "https://github.com/slouowzee/kapi"
  version "1.0.0-beta.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slouowzee/KAPI/releases/download/v1.0.0-beta.6/KAPI_darwin_amd64.tar.gz"
      sha256 "ac854154a80fadff5d2d410e7c960562fa15d13b99ffcb953266c8ee58509d86"

      define_method(:install) do
        bin.install "kapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slouowzee/KAPI/releases/download/v1.0.0-beta.6/KAPI_darwin_arm64.tar.gz"
      sha256 "ba0c5824a5ca2c7368c130478ad6eedefc877630429cd1258d0fbbe87685a78a"

      define_method(:install) do
        bin.install "kapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/slouowzee/KAPI/releases/download/v1.0.0-beta.6/KAPI_linux_amd64.tar.gz"
      sha256 "55c6d1108e7c23b705f488594ae238a30bd087b8267d7fabe5b6c8850a838146"
      define_method(:install) do
        bin.install "kapi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slouowzee/KAPI/releases/download/v1.0.0-beta.6/KAPI_linux_arm64.tar.gz"
      sha256 "274dcec511b4ba4d61ef5bbfedf77a9acb1fdc8944c742631a6f343603858e74"
      define_method(:install) do
        bin.install "kapi"
      end
    end
  end

  test do
    system "#{bin}/kapi --version"
  end
end
