# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kapi < Formula
  desc "A Go-based interactive TUI CLI for project scaffolding"
  homepage "https://github.com/slouowzee/kapi"
  version "1.0.0-beta.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slouowzee/KAPI/releases/download/v1.0.0-beta.9/KAPI_darwin_amd64.tar.gz"
      sha256 "23ead399ec977f5f470af6c3739fa6ad1dbb84afcec775b2313343064013d515"

      define_method(:install) do
        bin.install "kapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slouowzee/KAPI/releases/download/v1.0.0-beta.9/KAPI_darwin_arm64.tar.gz"
      sha256 "2156316d0f40825a48e541879b9099d60a8e760a11bb95bfedcd6b1ae37e037b"

      define_method(:install) do
        bin.install "kapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/slouowzee/KAPI/releases/download/v1.0.0-beta.9/KAPI_linux_amd64.tar.gz"
      sha256 "744eba79722a6f0f462830a258cc305b1f76645347da6087cb8e80ce60c898d3"
      define_method(:install) do
        bin.install "kapi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slouowzee/KAPI/releases/download/v1.0.0-beta.9/KAPI_linux_arm64.tar.gz"
      sha256 "b373249c2b48e558737535e3c6b2c24d0aeea87f4791f7179dc717e32c6bd722"
      define_method(:install) do
        bin.install "kapi"
      end
    end
  end

  test do
    system "#{bin}/kapi --version"
  end
end
