# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kapi < Formula
  desc "A Go-based interactive TUI CLI for project scaffolding"
  homepage "https://github.com/slouowzee/kapi"
  version "1.0.0-beta.1"

  on_macos do
    on_intel do
      url "https://github.com/slouowzee/KAPI/releases/download/v1.0.0-beta.1/KAPI_darwin_amd64.tar.gz"
      sha256 "bb83e50bbb5a6d183cdb8a033bbaed3aa946796e28445f92e7e67fcca1f8d946"

      def install
        bin.install "kapi"
      end
    end
    on_arm do
      url "https://github.com/slouowzee/KAPI/releases/download/v1.0.0-beta.1/KAPI_darwin_arm64.tar.gz"
      sha256 "dee47b7d9b8b967703bb3fd2694f6779316c2db13bc88c7dbda94bf9aa7a2e95"

      def install
        bin.install "kapi"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/slouowzee/KAPI/releases/download/v1.0.0-beta.1/KAPI_linux_amd64.tar.gz"
        sha256 "a385d75fc3e32c6a78246dda95588df5e7e877646fe5dd841ca4f8ab257cd640"

        def install
          bin.install "kapi"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/slouowzee/KAPI/releases/download/v1.0.0-beta.1/KAPI_linux_arm64.tar.gz"
        sha256 "9d6903aa4f8f46b462d0619cc94ea013f4ee18b8cef0ca7b609123e2a642815b"

        def install
          bin.install "kapi"
        end
      end
    end
  end

  test do
    system "#{bin}/kapi --version"
  end
end
